// Mock data constants for UNIMART

export const CATEGORIES = [
  { id: 'textbooks', name: 'Textbooks', icon: '📚', color: 'indigo' },
  { id: 'electronics', name: 'Electronics', icon: '💻', color: 'cyan' },
  { id: 'notes', name: 'Notes & Study Material', icon: '📝', color: 'purple' },
  { id: 'sports', name: 'Sports Equipment', icon: '⚽', color: 'emerald' },
  { id: 'accessories', name: 'Accessories', icon: '🎧', color: 'pink' },
  { id: 'hostel', name: 'Hostel Essentials', icon: '🛋️', color: 'amber' },
  { id: 'lab', name: 'Lab Equipment', icon: '🧪', color: 'rose' },
  { id: 'art', name: 'Art & Craft', icon: '🎨', color: 'orange' },
  { id: 'transport', name: 'Bicycles & Transport', icon: '🚲', color: 'teal' },
  { id: 'other', name: 'Other', icon: '📦', color: 'gray' },
];

export const CAMPUSES = [
  // Top Institutes
  'IIT Madras',
  'NIT Tiruchirappalli',
  'Anna University, Chennai',
  'Madras University',
  'Bharathiar University, Coimbatore',
  'Bharathidasan University, Tiruchirappalli',
  // Private Universities
  'VIT, Vellore',
  'SRM Institute of Science and Technology, Chennai',
  'SASTRA Deemed University, Thanjavur',
  'Amrita Vishwa Vidyapeetham, Coimbatore',
  'Vel Tech Rangarajan Dr. Sagunthala R&D Institute, Chennai',
  'Hindustan Institute of Technology and Science, Chennai',
  'Kalasalingam Academy of Research and Education, Srivilliputhur',
  'Shanmugha Arts Science Technology & Research Academy (SASTRA), Thanjavur',
  // Engineering Colleges
  'PSG College of Technology, Coimbatore',
  'College of Engineering, Guindy (CEG), Chennai',
  'Thiagarajar College of Engineering, Madurai',
  'Government College of Technology, Coimbatore',
  'Kongu Engineering College, Erode',
  'Mepco Schlenk Engineering College, Sivakasi',
  'Sri Sivasubramaniya Nadar College of Engineering, Kalavakkam',
  'Kumaraguru College of Technology, Coimbatore',
  'Sri Venkateswara College of Engineering, Sriperumbudur',
  'Rajalakshmi Engineering College, Chennai',
  'St. Joseph\'s College of Engineering, Chennai',
  'RMK Engineering College, Chennai',
  'Sathyabama Institute of Science and Technology, Chennai',
  'Saveetha Engineering College, Chennai',
  // Arts & Science Colleges
  'Loyola College, Chennai',
  'Madras Christian College, Chennai',
  'Presidency College, Chennai',
  'PSG College of Arts & Science, Coimbatore',
  'The American College, Madurai',
  'Bishop Heber College, Tiruchirappalli',
  'St. Xavier\'s College, Palayamkottai',
  'Ethiraj College for Women, Chennai',
  // Medical Colleges
  'Madras Medical College, Chennai',
  'Stanley Medical College, Chennai',
  'Kilpauk Medical College, Chennai',
  'Government Medical College, Coimbatore',
  // Law Colleges
  'Dr. Ambedkar Government Law College, Chennai',
  'School of Excellence in Law, Chennai',
];

export const ORDER_STATUS = {
  PENDING: 'pending',
  ACCEPTED: 'accepted',
  OTP_GENERATED: 'otp_generated',
  DELIVERED: 'delivered',
  CANCELLED: 'cancelled',
};

export const ORDER_STATUS_LABELS = {
  [ORDER_STATUS.PENDING]: { label: 'Pending', color: 'amber' },
  [ORDER_STATUS.ACCEPTED]: { label: 'Accepted', color: 'cyan' },
  [ORDER_STATUS.OTP_GENERATED]: { label: 'OTP Sent', color: 'purple' },
  [ORDER_STATUS.DELIVERED]: { label: 'Delivered', color: 'emerald' },
  [ORDER_STATUS.CANCELLED]: { label: 'Cancelled', color: 'rose' },
};

export const MOCK_USER = {
  id: 'stu_001',
  studentId: 'STU2024001',
  username: 'alex_doe',
  email: 'alex.doe@student.annauniv.edu',
  phone: '9876543210',
  campus: 'Anna University, Chennai',
  avatar: null,
  verified: true,
  createdAt: '2024-09-01',
};

export const MOCK_PRODUCTS = [
  {
    id: 'prod_001',
    title: 'Calculus: Early Transcendentals',
    description: 'James Stewart 8th Edition. Minor wear on cover, all pages intact. Perfect for MATH 101.',
    price: 450,
    category: 'textbooks',
    condition: 'Good',
    images: ['https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400'],
    seller: { username: 'math_nerd', campus: 'Anna University, Chennai' },
    status: 'available',
    createdAt: '2024-12-01',
  },
  {
    id: 'prod_002',
    title: 'MacBook Air M2 2023',
    description: 'Space Gray, 256GB, 8GB RAM. Battery health 94%. Comes with original charger and box.',
    price: 72000,
    category: 'electronics',
    condition: 'Like New',
    images: ['https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400'],
    seller: { username: 'tech_guru', campus: 'VIT, Vellore' },
    status: 'available',
    createdAt: '2024-11-28',
  },
  {
    id: 'prod_003',
    title: 'Organic Chemistry Notes Bundle',
    description: 'Complete handwritten + printed notes for CHEM 201/202. Includes solved problem sets.',
    price: 0,
    category: 'notes',
    condition: 'Excellent',
    images: ['https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=400'],
    seller: { username: 'chem_whiz', campus: 'IIT Madras' },
    status: 'available',
    createdAt: '2024-12-05',
  },
  {
    id: 'prod_005',
    title: 'Scientific Calculator TI-84 Plus',
    description: 'Texas Instruments TI-84 Plus CE. All functions work perfectly. Great for engineering courses.',
    price: 4500,
    category: 'electronics',
    condition: 'Good',
    images: ['https://images.unsplash.com/photo-1564466809058-bf4114d55352?w=400'],
    seller: { username: 'engi_pro', campus: 'NIT Tiruchirappalli' },
    status: 'available',
    createdAt: '2024-12-02',
  },
  {
    id: 'prod_007',
    title: 'Yoga Mat + Resistance Bands',
    description: 'Premium 6mm yoga mat with set of 5 resistance bands. Never used — gift I can\'t return.',
    price: 1500,
    category: 'sports',
    condition: 'New',
    images: ['https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=400'],
    seller: { username: 'fit_life', campus: 'SRM Institute of Science and Technology, Chennai' },
    status: 'available',
    createdAt: '2024-12-04',
  },
  {
    id: 'prod_010',
    title: 'Data Structures & Algorithms Textbook',
    description: 'CLRS Introduction to Algorithms 3rd Edition. Highlighted but otherwise great condition.',
    price: 350,
    category: 'textbooks',
    condition: 'Acceptable',
    images: ['https://images.unsplash.com/photo-1532012197267-da84d127e765?w=400'],
    seller: { username: 'cs_boss', campus: 'PSG College of Technology, Coimbatore' },
    status: 'available',
    createdAt: '2024-12-07',
  },
  {
    id: 'prod_011',
    title: 'Sony WH-1000XM5 Headphones',
    description: 'Noise-cancelling wireless headphones. Black. Includes carrying case and cable.',
    price: 18000,
    category: 'electronics',
    condition: 'Like New',
    images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400'],
    seller: { username: 'audio_fan', campus: 'Loyola College, Chennai' },
    status: 'sold',
    createdAt: '2024-11-25',
  },
  {
    id: 'prod_013',
    title: 'Engineering Drawing Kit',
    description: 'Complete drawing kit with drafter, compass set, and drawing sheets. Used for first year.',
    price: 800,
    category: 'other',
    condition: 'Good',
    images: ['https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400'],
    seller: { username: 'alex_doe', campus: 'Anna University, Chennai' },
    status: 'available',
    createdAt: '2024-12-09',
  },
  {
    id: 'prod_014',
    title: 'Physics Lab Manual',
    description: 'Lab manual for first-year physics. All experiments documented.',
    price: 0,
    category: 'notes',
    condition: 'Good',
    images: ['https://images.unsplash.com/photo-1585351737793-5e59e3b1bd53?w=400'],
    seller: { username: 'alex_doe', campus: 'Anna University, Chennai' },
    status: 'available',
    createdAt: '2024-12-10',
  },
];

export const MOCK_ORDERS = [
  {
    id: 'order_001',
    product: MOCK_PRODUCTS[0],
    buyer: { username: 'alex_doe', campus: 'Anna University, Chennai' },
    seller: { username: 'math_nerd', campus: 'Anna University, Chennai' },
    status: ORDER_STATUS.DELIVERED,
    otp: '482916',
    createdAt: '2024-12-02',
    deliveredAt: '2024-12-03',
  },
  {
    id: 'order_002',
    product: MOCK_PRODUCTS[1],
    buyer: { username: 'alex_doe', campus: 'Anna University, Chennai' },
    seller: { username: 'tech_guru', campus: 'VIT, Vellore' },
    status: ORDER_STATUS.OTP_GENERATED,
    otp: '739201',
    createdAt: '2024-12-05',
    deliveredAt: null,
  },
  {
    id: 'order_003',
    product: MOCK_PRODUCTS[3],
    buyer: { username: 'study_buddy', campus: 'NIT Tiruchirappalli' },
    seller: { username: 'alex_doe', campus: 'Anna University, Chennai' },
    status: ORDER_STATUS.PENDING,
    otp: null,
    createdAt: '2024-12-08',
    deliveredAt: null,
  },
];

export const MOCK_MESSAGES = [
  {
    id: 'msg_001',
    orderId: 'order_001',
    sender: 'alex_doe',
    text: 'Hey! When can we meet for the book exchange?',
    timestamp: '2024-12-02T10:30:00',
  },
  {
    id: 'msg_002',
    orderId: 'order_001',
    sender: 'math_nerd',
    text: 'How about tomorrow at the library entrance at 2 PM?',
    timestamp: '2024-12-02T10:35:00',
  },
  {
    id: 'msg_003',
    orderId: 'order_001',
    sender: 'alex_doe',
    text: 'Perfect! I\'ll be there. Thanks! 📚',
    timestamp: '2024-12-02T10:40:00',
  },
  {
    id: 'msg_004',
    orderId: 'order_002',
    sender: 'alex_doe',
    text: 'Hi! I placed the order for the MacBook. Can we arrange delivery?',
    timestamp: '2024-12-05T14:00:00',
  },
  {
    id: 'msg_005',
    orderId: 'order_002',
    sender: 'tech_guru',
    text: 'Sure! I\'ll be at the student center from 3-5 PM today.',
    timestamp: '2024-12-05T14:10:00',
  },
];

export const CONDITION_OPTIONS = ['New', 'Like New', 'Excellent', 'Good', 'Acceptable'];

export const SORT_OPTIONS = [
  { value: 'newest', label: 'Newest First' },
  { value: 'oldest', label: 'Oldest First' },
  { value: 'price-low', label: 'Price: Low to High' },
  { value: 'price-high', label: 'Price: High to Low' },
];
